const { codeBlock } = require("discord.js");

var format = [
    '"The "+pick(adjective)',
    'pick(adjective)+" "+pick(adjective)',
    'pick(adjective)+" "+pick(noun)',
    'pick(adjective)+" "+pick(place)',
    '"2 "+pick(adjective)+" 2 "+pick(verb)',
    'pick(adjective)+" 4 Life"',
    'pick(adjective)+" Lives Matter"',
    '"Team "+pick(adjective)',
    '"Team "+pick(noun)',
    '"Team "+pick(place)',
    'pick(noun)+" With "+pick(adjective)+" "+pick(noun)',
    'pick(noun)+" With "+pick(noun)',
    'pick(noun)+" From "+pick(place)',
    'pick(noun)+" "+pick(verb)',
    'pick(noun)+" Don’t "+pick(verb)',
    'pick(place)+" "+pick(noun)',
    'pick(place)+"’s "+pick(adjective)+" "+pick(noun)',
    'pick(place)+"’s Finest"',
    'pick(verb)+" & "+pick(verb)',
    '"Keep Calm & "+pick(verb)',
    '"I got this " +pick(noun)+" on Facebook marketplace"',
    '"Get that " +pick(noun)+" out yo mouth"',
    '"I got a coupon for "+pick(adjective)+" "+pick(noun)',
  ],
  adjective = [
    // the…
    "Delinquent",
    "Surprising",
    "Unstoppable",
    "Great-Canadian",
    "Trivial",
    "Undefeated",
    "Ghetto",
    "Awesome",
    "Mighty",
    "Ratchet",
    "Neglectful",
    "Supreme",
    "Almost-Ready-To-Play",
    "PC",
    "[TRIGGERED]",
    "Microagressive",
    "Brave",
    "Top-Secret",
    "Metric",
    "Hood-Rich",
    "Ballin’",
    "Twerking-Class",
    "Raging",
    "Trill",
    "#Winning",
    "Twerking",
    "Micro-Managing",
    "Dank",
    "Privileged",
    "Omniscient",
    "College-Educated",
    "Real",
    "Royal",
    "Inappropriate",
    "Offensive",
    "Raunchy",
    "Absurd",
    "Hilarious",
    "Twisted",
    "Vulgar",
    "Nonsensical",
    "Crude",
    "Outrageous",
    "Bizarre",
    "Shocking",
    "Ludicrous",
    "Disgusting",
    "Offensive",
    "Irreverent",
    "Wacky",
    "Absurd",
    "Insane",
    "Provocative",
    "Grotesque",
    "Rude",
    "Obscene",
    "Repulsive",
    "Twisted",
    "Scandalous",
    "Outlandish",
    "Crass",
    "Filthy",
    "Unconventional",
    "Controversial",
    "Contemptible",
    "Perverse",
    "Witty",
    "Tasteless",
    "Nasty",
    "Shocking",
    "Edgy",
    "Sick",
    "Depraved",
    "Outrageous",
    "Racy",
    "Deranged",
    "Diabolical",
    "Offensive",
    "Contemptuous",
    "Hysterical",
    "Vulgar",
    "Cringe-worthy",
    "Disturbing",
    "Freakish",
    "Lewd",
    "Perverted",
    "Ridiculous",
    "Sordid",
    "Nonsensical",
    "Cynical",
    "Derogatory",
    "Risible",
    "Indecent",
    "Contemptuous",
    "Disgraceful",
    "Immoral",
    "Scatological",
    "Ribald",
    "Wicked",
    "Foul",
    "Hateful",
    "Outrageous",
    "Profane",
    "Scandalous",
    "Tawdry",
    "Unhinged",
    "Distasteful",
    "Satirical",
    "Sinister",
    "Insulting",
    "Offensive",
    "Contemptible",
    "Shameful",
    "Vulgar",
    "Crude",
    "Abhorrent",
    "Repugnant",
    "Ludicrous",
    "Inflammatory",
    "Depraved",
    "Filthy",
    "Obscene",
    "Outlandish",
    "Shocking",
    "Twisted",
    "Controversial",
    "Grotesque",
    "Disgusting",
    "Diabolical",
    "Hysterical",
    "Scatological",
    "Abominable",
    "Irreverent",
    "Outrageous",
    "Silly",
    "Crazy",
    "Lunatic",
    "Loony",
    "Ridiculous",
    "Unbelievable",
    "Mad",
    "Nonsensical",
    "Absurd",
    "Cranky",
    "Funky",
    "Offbeat",
    "Absurd",
    "Kooky",
    "Maniacal",
    "Weird",
    "Whacky",
    "Wild",
    "Bawdy",
    "Odd",
    "Deranged",
    "Nutty",
    "Batty",
    "Giddy",
    "Weirdest",
    "Stupid",
    "Absurdity",
    "Insanely",
    "Asinine",
    "Ludicrousness",
    "Freaky",
    "Wackiest",
    "Bonkers",
    "Wackadoodle",
    "Oddly",
    "Bonkersville",
    "Hilariously",
    "Weirder",
    "Ludicrously",
    "Unconventional",
    "Bizarro",
    "Gonzo",
    "Craziness",
    "Far-out",
    "Unhinged",
    "Nuttiness",
    "Outlandishly",
    "Hilariously",
    "Hooey",
    "Gobbledygook",
    "Surreal",
    "Bizarreness",
    "Kookaburra",
    "Crazily",
    "Doozy",
    "Foolishness",
    "Silly-willy",
    "Goofiness",
    "Madcap",
    "Doodad",
    "Whimsy-filled",
    "Cuckoo",
    "Zanyism",
    "Gobbledygook-filled",
    "Humorous",
    "Kookery",
    "Nuttiness",
    "Tomfoolery",
    "Whimsicality",
    "Bunkers",
    "Laughtastic",
    "Ridiculosity",
    "Silliness",
    "Bamboozlement",
    "Bunkum",
    "Gobbledygookery",
    "Jocularity",
    "Malarkey",
    "Zaniness",
    "Shenanigans",
    "Nonsense",
    "Noodlehead",
    "Flummox",
    "Gigglefest",
    "Gobbledegook",
    "Baffling",
    "Bloviation",
    "Flapdoodle",
    "Bosh",
    "Hokum",
    "Ridiculitude",
    "Hullabaloo",
    "Quirkiness",
    "Hootenanny",
    "Higgledy-piggledy",
    "Shenaniganism",
    "Fiddle-faddle",
    "Ballyhoo",
    "Riffraff",
    "Gobbledygookism",
    "Hijinks",
    "Woolly-headed",
    "Flibbertigibbet",
    "Balderdash",
    "Jiggery-pokery",
    "Poppycock",
    "Codswallop",
    "Lallygag",
    "Wheedle",
    "Bamboozle",
    "Fandango",
    "Mishmash",
    "Brouhaha",
    "Razzmatazz",
    "Hocus-pocus",
    "Ballyhooed",
    "Flapdoodlery",
    "Hootenannied",
    "Helter-skelter",
    "Discombobulate",
    "Jellybean",
    "Shilly-shally",
    "Lollygag",
    "Shillyshallying",
    "Topsy-turvy",
    "Higgledypiggledy",
    "Scurryfunge",
    "Bibble-babble",
    "Hippity-hop",
    "Nudiustertian",
    "Hooty",
    "Sesquipedalian",
    "Wibbly-wobbly",
    "Pandemonium",
    "Whimsywhamsy",
    "Willy-nilly",
    "Gobsmacked",
    "Higgledy-pokery",
    "Helter-skelter",
    "Jiggery-pokery",
    "Snickersnee",
    "Snicklefritz",
    "Nincompoopery",
    "Whippersnapper",
    "Sesquipedalianism",
  ],
  noun = [
    // the…
    "Beavers",
    "Buffaloons",
    "Crew",
    "Executives",
    "Squad",
    "Cultural Appropriation",
    "Tumblristas",
    "Patriots",
    "Alex Trebek",
    "Yankees",
    "Canucks",
    "Babes",
    "OGs",
    "1%",
    "Wikipedians",
    "Thugs",
    "Gangsters",
    "Microagressions",
    "Warriors",
    "Trigger Warning",
    "Bernie Sanders",
    "Unicorn",
    "Fart",
    "Penguin",
    "Banana",
    "Butt",
    "Kitten",
    "Pickle",
    "Zombie",
    "Robot",
    "Dinosaur",
    "Ninja",
    "Monkey",
    "Pirate",
    "Clown",
    "Burger",
    "Toilet",
    "Vampire",
    "Taco",
    "Llama",
    "Spaceship",
    "Pancake",
    "Squirrel",
    "Mermaid",
    "Alien",
    "Muffin",
    "Cactus",
    "Mustache",
    "Leprechaun",
    "Donkey",
    "Octopus",
    "T-Rex",
    "Rainbow",
    "Sausage",
    "Pizza",
    "Unicycle",
    "Giraffe",
    "Chainsaw",
    "Wombat",
    "Sloth",
    "Panda",
    "Duck",
    "Elephant",
    "Chicken",
    "Kangaroo",
    "Cucumber",
    "Goblin",
    "Ostrich",
    "Cabbage",
    "Sushi",
    "Penguin",
    "Pig",
    "Gnome",
    "Sword",
    "Hedgehog",
    "Noodle",
    "Hamster",
    "Waffle",
    "Eggplant",
    "Koala",
    "Moose",
    "Platypus",
    "Jellyfish",
    "Lobster",
    "Raccoon",
    "Bagel",
    "Squid",
    "Narwhal",
    "Cthulhu",
    "Whale",
    "Pineapple",
    "Corgi",
    "Pancake",
    "Puppy",
    "Oreo",
    "Ketchup",
    "Mongoose",
    "Dragon",
    "Nunchucks",
    "Tofu",
    "Sloth",
    "Sledgehammer",
    "Yeti",
    "Giraffe",
    "Tuba",
    "Pufferfish",
    "Flamingo",
    "Pajamas",
    "Gorilla",
    "Ewok",
    "Chinchilla",
    "Molasses",
    "Liger",
    "Bagpipes",
    "Gargamel",
    "Napkin",
    "Gerbil",
    "Jellybean",
    "Pajamas",
    "Sasquatch",
    "Trombone",
    "Fruitcake",
    "Popsicle",
    "Hobbit",
    "Kazoo",
    "Spaceship",
    "Spatula",
    "Pickle",
    "Cheeseburger",
    "Potato",
    "Marshmallow",
    "Popcorn",
    "Flamethrower",
    "Rhinoceros",
    "Hedgehog",
    "Toothpaste",
    "Blimp",
    "Cannibal",
    "Leprechaun",
    "Toupee",
    "Lawnmower",
    "Rhinoceros",
    "Pogo stick",
    "Pumpkin",
    "Slinky",
    "Sweater",
    "Tapeworm",
    "Broomstick",
    "Chainsaw",
    "Kitten mittens",
    "Tumbleweed",
    "Yogurt",
    "Astronaut",
    "Bubble wrap",
    "Chicken nugget",
    "Dingleberry",
    "Disco ball",
    "Gerbil",
    "Hippie",
    "Lawn gnome",
    "Lobster",
    "Noodle",
    "Pogo stick",
    "Pumpkin spice",
    "Sasquatch",
    "Squirrel",
    "Trombone",
    "Velociraptor",
    "Wombat",
    "Zamboni",
    "Bazooka",
    "Cockroach",
    "Dingleberry",
    "Disco ball",
    "Lawn gnome",
    "Mustache",
    "Pogo stick",
    "Pumpkin spice",
    "Rhinestone",
    "Sasquatch",
    "Velociraptor",
    "Wombat",
    "Zamboni",
    "Bazooka",
    "Cockroach",
    "Dingleberry",
    "Disco ball",
    "Lawn gnome",
    "Mustache",
    "Pogo stick",
    "Pumpkin spice",
    "Rhinestone",
    "Sasquatch",
    "Velociraptor",
    "Wombat",
    "Zamboni",
  ],
  place = [
    // from…
    "Toronto",
    "Buffalo",
    "America",
    "Canada",
    "Earth",
    "Tumblr",
    "The Internet",
    "The Past",
    "Space",
    "Nowhere",
    "The Right-Side-of-History",
    "The Trap",
    "Wikipedia",
    "The Streets",
    "The Occident",
    "The 6",
    "First-Class",
    "An Alternate Universe",
    "Hell",
    "The Moon",
    "Narnia",
    "Chernobyl",
    "Mordor",
    "Wonderland",
    "The White House",
    "Atlantis",
    "Bikini Bottom",
    "The Bermuda Triangle",
    "Jurassic Park",
    "The Forbidden Forest",
    "Hogwarts",
    "The Batcave",
    "Oz",
    "The Upside Down",
    "Bikini Atoll",
    "Neverland",
    "The Shire",
    "R'lyeh",
    "The Matrix",
    "Gotham City",
    "Westeros",
    "Sesame Street",
    "Hyrule",
    "Whoville",
    "Zombieland",
    "Naboo",
    "Springfield",
    "The TARDIS",
    "The Death Star",
    "Sunnydale",
    "Middle-earth",
    "Zion",
    "The Emerald City",
    "Area 51",
    "Xanadu",
    "A Parallel Universe",
    "The Twilight Zone",
    "The Dark Web",
    "Silent Hill",
    "Salem's Lot",
    "The Hundred Acre Wood",
    "The Overlook Hotel",
    "Emerald City",
    "Apostrophe Island",
    "Bizarro World",
    "Lilliput",
    "The Hollow Earth",
    "Pandora",
    "Elbonia",
    "The Phantom Zone",
    "The Shangri-La",
    "The Lost City of Gold",
    "Willy Wonka's Chocolate Factory",
    "A Galaxy Far, Far Away",
    "The Red Light District",
    "Downton Abbey",
    "The Playboy Mansion",
    "The Dark Side of the Moon",
    "Black Hole",
    "The Roaring Twenties",
    "The Wild West",
    "The Alamo",
    "The Land of Oz",
    "The Enchanted Forest",
    "Kingdom of Hearts",
    "The Mushroom Kingdom",
    "The Forbidden City",
    "The Vatican",
    "The Land of Nod",
    "The Land of Make-Believe",
    "The Swiss Alps",
    "The Great Barrier Reef",
    "The Amazon Rainforest",
    "The Sahara Desert",
    "The Grand Canyon",
    "The Great Wall of China",
    "The Eiffel Tower",
    "The Statue of Liberty",
    "The Taj Mahal",
    "The Colosseum",
    "The Acropolis",
    "The Louvre",
    "The Sydney Opera House",
    "The Pyramids of Egypt",
    "The Hanging Gardens of Babylon",
    "The Garden of Eden",
    "The Lost City of Atlantis",
    "The Fountain of Youth",
    "The Holy Grail",
    "The Sword in the Stone",
    "The Cave of Wonders",
    "The Black Forest",
    "The Dead Sea",
    "The Marianas Trench",
    "The Galapagos Islands",
    "The Arctic Circle",
    "The Antarctic Peninsula",
    "The Great Rift Valley",
    "The Andes Mountains",
    "The Himalayas",
    "The Rocky Mountains",
    "The Alps",
    "The Sahara Desert",
    "The Gobi Desert",
    "The Kalahari Desert",
    "The Arabian Desert",
    "The Mojave Desert",
    "The Atacama Desert",
    "The Sonoran Desert",
    "The Serengeti Plains",
    "The African Savannah",
    "The Australian Outback",
    "The Siberian Tundra",
    "The Taiga Forest",
    "The Rainforests of Borneo",
    "The Coral Reefs of Fiji",
    "The Caves of Lascaux",
    "The Cliffs of Moher",
    "The Great Ocean Road",
    "The Inca Trail",
    "The Silk Road",
    "The Trans-Siberian Railway",
    "The Appalachian Trail",
    "The Pacific Crest Trail",
    "The Camino de Santiago",
    "Route 66",
    "The Orient Express",
    "The Silk Road",
    "The Trans-Siberian Railway",
    "The Appalachian Trail",
    "The Pacific Crest Trail",
    "The Camino de Santiago",
    "Route 66",
    "The Orient Express",
    "The Matterhorn",
    "The Angel Falls",
    "The Victoria Falls",
    "Mount Everest Base Camp",
    "Loch Ness",
    "Niagara Falls",
    "The Parthenon",
    "Machu Picchu",
    "The Petra",
    "Stonehenge",
    "The Angkor Wat",
    "Easter Island",
    "The Venice Canals",
    "Santorini",
    "The Cinque Terre",
    "The Bali Rice Terraces",
    "Santorini",
  ],
  verb = [
    // who…
    "Destroy",
    "Can’t Even",
    "Win",
    "Have Guns",
    "Get Jokes",
    "Know Things",
    "Trivialize",
    "Lift",
    "Guess Well",
    "Lawyer Up",
    "Care",
    "Squish",
    "Tickle",
    "Punch",
    "Summon",
    "Wrestle",
    "Tickle",
    "Twerk",
    "Lick",
    "Spank",
    "Chase",
    "Slap",
    "Bribe",
    "Steal",
    "Prank",
    "Belly flop",
    "Moonwalk",
    "Facepalm",
    "Serenade",
    "Moon",
    "Binge-watch",
    "Zap",
    "Swallow",
    "Pretend",
    "Fart",
    "Burp",
    "Whisper",
    "Roast",
    "Booty dance",
    "Twirl",
    "Strangle",
    "Scream",
    "Flirt with",
    "Propose to",
    "Tickle",
    "Massage",
    "Confess to",
    "Kidnap",
    "Annoy",
    "Hypnotize",
    "Kiss",
    "Taser",
    "Hug",
    "Pretend to be",
    "Marry",
    "Photobomb",
    "Shush",
    "Stalk",
    "Seduce",
    "Tape",
    "Swat",
    "Dance with",
    "Lap dance",
    "Barf on",
    "Moon",
    "Steal from",
    "Peek at",
    "Spank",
    "High-five",
    "Flip off",
    "Bite",
    "Hiccup on",
    "Vomit on",
    "Burp in the face of",
    "Moonwalk with",
    "Tickle",
    "Twerk on",
    "Lick",
    "Spank",
    "Chase",
    "Slap",
    "Bribe",
    "Steal",
    "Prank",
    "Belly flop",
    "Moonwalk",
    "Facepalm",
    "Serenade",
    "Moon",
    "Binge-watch",
    "Zap",
    "Swallow",
    "Pretend",
    "Fart",
    "Burp",
    "Whisper",
    "Roast",
    "Booty dance",
    "Twirl",
    "Strangle",
    "Scream",
    "Flirt with",
    "Propose to",
    "Tickle",
    "Massage",
    "Confess to",
    "Kidnap",
    "Annoy",
    "Hypnotize",
    "Kiss",
    "Taser",
    "Hug",
    "Pretend to be",
    "Marry",
    "Photobomb",
    "Shush",
    "Stalk",
    "Seduce",
    "Tape",
    "Swat",
    "Dance with",
    "Lap dance",
    "Barf on",
    "Moon",
    "Steal from",
    "Peek at",
    "Spank",
    "High-five",
    "Flip off",
    "Bite",
    "Hiccup on",
    "Vomit on",
    "Burp in the face of",
    "Moonwalk with",
    "Twerk on",
    "Lick",
    "Fuck",
    "Spank",
    "Chase",
    "Slap",
    "Bribe",
    "Steal",
    "Prank",
    "Belly flop",
    "Moonwalk",
    "Facepalm",
    "Serenade",
    "Moon",
    "Binge-watch",
    "Zap",
    "Swallow",
    "Pretend",
    "Fart",
    "Burp",
    "Whisper",
    "Roast",
    "Booty dance",
    "Twirl",
    "Strangle",
    "Scream",
    "Flirt with",
    "Propose to",
    "Tickle",
    "Massage",
    "Confess to",
    "Kidnap",
    "Annoy",
    "Hypnotize",
    "Kiss",
    "Taser",
    "Hug",
    "Pretend to be",
    "Marry",
    "Photobomb",
    "Shush",
    "Stalk",
    "Seduce",
    "Tape",
    "Swat",
    "Boop",
    "Dance with",
    "Lap dance",
    "Barf on",
    "Moon",
    "Steal from",
    "Peek at",
    "Spank",
    "High-five",
    "Flip off",
    "Bite",
    "Hiccup on",
    "Vomit on",
    "Burp in the face of",
    "Moonwalk with",
    "Twerk on",
    "Lick",
    "Spank",
    "Chase",
    "Slap",
    "Bribe",
    "Steal",
    "Prank",
    "Belly flop",
    "Moonwalk",
    "Facepalm",
    "Serenade",
    "Moon",
    "Binge-watch",
    "Zap",
    "Swallow",
    "Pretend",
    "Fart",
    "Burp",
    "Whisper",
    "Roast",
    "Booty dance",
    "Twirl",
    "Strangle",
    "Scream",
    "Flirt with",
    "Propose to",
    "Tickle",
    "Massage",
    "Confess to",
    "Kidnap",
    "Annoy",
    "Hypnotize",
    "Kiss",
    "Taser",
    "Hug",
    "Pretend to be",
    "Marry",
    "Photobomb",
    "Shush",
    "Stalk",
    "Seduce",
    "Tape",
    "Swat",
    "Dance with",
    "Lap dance",
    "Barf on",
    "Moon",
    "Steal from",
    "Peek at",
    "Spank",
    "High-five",
    "Flip off",
    "Bite",
    "Hiccup on",
    "Vomit on",
    "Burp in the face of",
    "Moonwalk with",
    "Twerk on",
  ];

function pick(id) {
  return id[Math.floor(Math.random() * id.length)];
}

exports.generate = () => {
  var teamNames = [];
  for (i = 0; i < 5; i++) {
    teamNames.push(eval(format[Math.floor(Math.random() * format.length)]));
  }

  return codeBlock(
    "\n1: " +
      teamNames[0] +
      "\n2: " +
      teamNames[1] +
      "\n3: " +
      teamNames[2] +
      "\n4: " +
      teamNames[3] +
      "\n5: " +
      teamNames[4]
  );
};
